#!/bin/sh
#
# @name Generic Hexarotor v827
#
# @type Hexarotor +
# @class Copter
#
# @output MAIN1 motor1
# @output MAIN2 motor2
# @output MAIN3 motor3
# @output MAIN4 motor4
# @output MAIN5 motor5
# @output MAIN6 motor6
# @maintainer Lorenz Meier <lorenz@px4.io>
#
# @board intel_aerofc-v1 exclude
# @board bitcraze_crazyflie exclude
#

sh /etc/init.d/rc.v827

set MIXER v827

# Need to set all 8 channels
set PWM_OUT 12345678
